// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArqkWNTioj5OtwLCQZdKoAv9M4gzaOWgM',
    appId: '1:836198677543:web:795112ae20fdef4dac2202',
    messagingSenderId: '836198677543',
    projectId: 'comix-trackerz-38d13',
    authDomain: 'comix-trackerz-38d13.firebaseapp.com',
    storageBucket: 'comix-trackerz-38d13.appspot.com',
    measurementId: 'G-B0J0TPZ7GB',
    databaseURL: 'https://comix-trackerz-38d13-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8DVO_e6fB8VobEoTqE9Z1_15g5cl9InM',
    appId: '1:836198677543:android:722932b6c8543ddcac2202',
    messagingSenderId: '836198677543',
    projectId: 'comix-trackerz-38d13',
    storageBucket: 'comix-trackerz-38d13.appspot.com',
    databaseURL: 'https://comix-trackerz-38d13-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4TkLwy7sGdePBhEDVOUVt5prBEFYX2ms',
    appId: '1:836198677543:ios:d28966e9806d4358ac2202',
    messagingSenderId: '836198677543',
    projectId: 'comix-trackerz-38d13',
    storageBucket: 'comix-trackerz-38d13.appspot.com',
    iosBundleId: 'com.rafael.comixTrackerz',
    databaseURL: 'https://comix-trackerz-38d13-default-rtdb.firebaseio.com',
  );

}